services:
    _defaults: { public: true }

    maxbeckers_amazon_alexa.request_validator:
        class: MaxBeckers\AmazonAlexa\Validation\RequestValidator

    maxbeckers_amazon_alexa.request_handler_registry:
        class: MaxBeckers\AmazonAlexa\RequestHandler\RequestHandlerRegistry

    maxbeckers_amazon_alexa.response_helper:
        class: MaxBeckers\AmazonAlexa\Helper\ResponseHelper

    maxbeckers_amazon_alexa.request_transformer:
        class: MaxBeckers\AmazonAlexaBundle\RequestTransformer\RequestTransformer
        arguments:
            - '@maxbeckers_amazon_alexa.request_handler_registry'
            - '@maxbeckers_amazon_alexa.request_validator'
            - '@request_stack'

    maxbeckers_amazon_alexa.ssml_generator:
        class: MaxBeckers\AmazonAlexa\Helper\SsmlGenerator
